export interface Magazine {
  id: string;
  name: string;
  gender: "male" | "female" | "unisex";
  coverStarGender?: "male" | "female";
  category: "luxury" | "fitness" | "business" | "tech" | "lifestyle" | "street";
  
  // VISUAL IDENTITY
  uiFont: string;        // CSS font-family string, e.g. "'Playfair Display', serif"
  uiFontWeight: string;  // CSS font-weight, e.g. "700" or "900"
  primaryColor: string;
  accentColor: string;
  fontStyle: string;
  logoStyle: string;
  logoColor: string;
  thumbnail: string;
  thumbnailMale?: string;
  thumbnailFemale?: string;

  // BRAND DNA
  editorialPersona: string;
  targetAudience: string;
  tone: string;
  focus: string;
  iconicElement: string;
  priceSegment: "budget" | "mid" | "premium" | "luxury";
  
  // COVER LAYOUT DNA
  coverLayoutDescription: string;
  textDensity: "minimal" | "moderate" | "dense";
  sublineCount: { min: number; max: number };
  
  // SPATIAL & VISUAL RULES  
  spatialGrid: string;
  materialFinish: string;
  lightingDna: string;
  typographyLayout: string;
  
  // COVER TEXT RULES
  logoPlacement: string;
  headlineRules: string;
  sublineCategories: string[];
  coverTextStyle: string;
  colorInstructions: string;
  
  // FASHION/POSE GUIDE
  clothingGuide: string;
  poseGuide: string;
  backgroundGuide: string;
  
  // FEW-SHOT REFERENCES
  referenceHeadlines: string[];
  referenceSublines: string[];
}

export const MAGAZINES: Magazine[] = [
  {
    id: "vogue",
    name: "Vogue",
    uiFont: "'Playfair Display', serif",
    uiFontWeight: "700",
    gender: "female",
    category: "luxury",
    primaryColor: "#000000",
    accentColor: "#D4AF37",
    fontStyle: "Didot/Bodoni serif",
    logoStyle: "Serif ALL-CAPS",
    logoColor: "White/Black",
    thumbnail: "/thumbnails/vogue.jpg",
    editorialPersona: "You are the Art Director of Vogue, the world's most authoritative fashion publication. You think in terms of high-fashion, art, and cultural authority. Every word is a statement. Less is always more. You never use numbers in headlines. You never use exclamation marks. Your tone is elegant, commanding, and museum-like.",
    targetAudience: "Elite women 25-45, fashion industry insiders, luxury consumers, art collectors",
    tone: "Authoritative, elegant, unapologetic, artistic, cultural",
    focus: "High fashion as art, trendsetting, designer profiles, cultural commentary",
    iconicElement: "The September Issue, logo partially obscured by model's head, minimal text",
    priceSegment: "luxury",
    coverLayoutDescription: "Clean, high-fashion aesthetic. Logo partially obscured. Minimal headlines.",
    textDensity: "minimal",
    sublineCount: { min: 2, max: 3 },
    spatialGrid: "Strict vertical hierarchy. TOP 12%: VOGUE logo centered. LEFT 10-30%, BOTTOM 60-85%: 2-3 cover lines. RIGHT SIDE: completely empty. Text coverage under 12% of total area. Subject fills 85-95% of frame, centered or slightly left.",
    materialFinish: "Ultra-premium high-gloss UV coating, 130lb silk paper stock, deep ink saturation with rich blacks. Subtle paper texture visible on close inspection. Colors are vivid but never garish.",
    lightingDna: "Cinematic butterfly lighting, 5600K key light with large soft-box directly above and slightly in front of subject. Subtle fill from below. Deep sculpted shadows under cheekbones and jawline. High-end editorial contrast. Skin has luminous quality without being overlit.",
    typographyLayout: "VOGUE: Didot/Bodoni, 72-80pt, ALL-CAPS, tracking +200. Headlines: Helvetica Neue Light, 9-11pt. Sublines: same font, 7-8pt. All flush-left. Extreme weight contrast between logo and body text.",
    logoPlacement: "The word 'VOGUE' in large Didot/Bodoni serif ALL-CAPS, tracked very wide (+200), centered horizontally in the top 12% of the frame. The subject's head/hair MUST partially overlap the bottom portion of at least 2-3 letters, creating a 3D layered depth effect. Color: white or black depending on background contrast.",
    headlineRules: "One powerful short phrase or single evocative word. Never playful. Never uses numbers. Never has exclamation marks. Feels like a gallery exhibition title or a fashion manifesto. Maximum 4 words.",
    sublineCategories: ["FASHION", "BEAUTY", "CULTURE", "DESIGN", "ART"],
    coverTextStyle: "Headlines: 9-11pt thin sans-serif (like Helvetica Neue Light), flush-left in the lower-left corner, stacked in an elegant column with generous leading. Color: white with a very subtle drop shadow for readability. The RIGHT SIDE of the cover must remain completely clean — no text. Date and price: 6pt, bottom edge, nearly invisible.",
    colorInstructions: "Dominant palette: neutral tones — black, white, cream, champagne gold (#D4AF37) as rare accent. Never bright colors on text. Background can be any color but must feel editorial and elevated.",
    clothingGuide: "Haute couture or high-end designer pieces. Think Chanel, Dior, Valentino, Balenciaga. Structured garments, architectural silhouettes, or flowing evening gowns. Minimal accessories — one statement piece maximum. No casual wear, no streetwear, no athletic wear.",
    poseGuide: "Regal and composed. Standing tall with perfect posture, or seated with architectural elegance. Direct gaze into camera lens or a slightly elevated chin with confidence. Minimal hand gestures. The pose should feel like a sculpture — still, powerful, deliberate. Never playful, never casual.",
    backgroundGuide: "Clean studio background — solid color (white, cream, pale gray, or bold single color), or minimal architectural element. Never busy, never outdoor nature scenes.",
    referenceHeadlines: ["The New Elegance", "Redefining Power", "A Vision in Light", "The Art of Now", "Pure Form", "Timeless", "The Statement", "Beyond Beauty", "Eternal", "The Revolution"],
    referenceSublines: ["FASHION | The designers reshaping the silhouette", "BEAUTY | A new standard of luminosity", "CULTURE | When fashion meets architecture", "DESIGN | The next wave of creative directors", "ART | Museums embrace the runway", "FASHION | The power of the perfect cut", "BEAUTY | Skin as canvas", "CULTURE | The voices defining this decade"]
  },
  {
    id: "elle",
    name: "Elle",
    uiFont: "'Bebas Neue', sans-serif",
    uiFontWeight: "400",
    gender: "female",
    category: "luxury",
    primaryColor: "#000000",
    accentColor: "#E11D48",
    fontStyle: "Bold geometric sans-serif",
    logoStyle: "Bold sans-serif ALL-CAPS",
    logoColor: "White/Black/Red",
    thumbnail: "/thumbnails/elle.jpg",
    editorialPersona: "You are the Editor-in-Chief of Elle. You bridge high fashion with accessibility. You're energetic, optimistic, international. You love mixing bold typography with vibrant energy. You use short punchy phrases and sometimes numbers for listicles. You celebrate real women alongside supermodels.",
    targetAudience: "Young women 18-35, fashion-forward but practical, international mindset",
    tone: "Energetic, optimistic, accessible, modern, international",
    focus: "Accessible high fashion, real women, international trends, practical style advice",
    iconicElement: "Bold ELLE logo always fully visible, dynamic poses, vibrant colors, 45+ international editions",
    priceSegment: "mid",
    coverLayoutDescription: "Modern and vibrant. Logo is prominent. Headlines are bold and often use a mix of font weights.",
    textDensity: "moderate",
    sublineCount: { min: 4, max: 6 },
    spatialGrid: "Dynamic composition. Logo TOP 10% fully visible. Main headline LEFT of model, 40-60% height. 4-6 secondary lines scattered LEFT and RIGHT margins. Subject centered with room for text on sides.",
    materialFinish: "Semi-gloss finish, smooth magazine stock, vibrant color reproduction with punchy saturation.",
    lightingDna: "High-key fashion lighting, 5000K, vibrant and clean, minimal shadows. Two large softboxes at 45-degree angles. Fill light from front. Skin looks radiant and energetic. Colors pop.",
    typographyLayout: "ELLE: Bold geometric sans-serif, 60-70pt, ALL-CAPS. Headlines: mix of bold and light weights of same sans-serif family, 14-18pt. Sublines: 8-10pt. Dynamic spacing and alignment.",
    logoPlacement: "'ELLE' in bold sans-serif ALL-CAPS, very large and ALWAYS fully visible (never obscured by subject). Positioned in top 10%, centered. Color: white, black, or red depending on contrast.",
    headlineRules: "Short punchy phrases, can include numbers for listicles. Bold and energetic. Uses a mix of font weights — one word bold, next word light. Maximum 5 words. Can end with '!'.",
    sublineCategories: ["STYLE", "BEAUTY", "FASHION", "TRENDS", "CULTURE", "TRAVEL"],
    coverTextStyle: "Headlines: Bold sans-serif mixed weights, 14-18pt for main headline, 9-11pt for secondary. Positioned LEFT of model for main headline (large), scattered LEFT and RIGHT for secondary lines. Colors: mix of white, yellow (#FFD700), and hot pink. Dynamic layout — not rigid columns.",
    colorInstructions: "Vibrant and contrasting. Text colors: white, yellow, hot pink, occasionally red. Background: bright, energetic — can be bold single color or fashion-forward setting. Never muted or somber.",
    clothingGuide: "Modern designer wear that feels accessible — not overly avant-garde. Think Zara x high-end collaborations. Blazers with edge, statement dresses, chic separates. A mix of designer and accessible-luxury. Can be colorful and bold.",
    poseGuide: "Dynamic and energetic. Walking toward camera, hair with movement, a confident smile or expressive look. Body in motion or with a sense of energy. Can have one hand on hip, adjusting sunglasses, or mid-stride.",
    backgroundGuide: "Can be studio (bright colors) or fashion-forward location. Urban, modern, vibrant. Never too dark or somber.",
    referenceHeadlines: ["STYLE SPECIAL", "100 Best Looks", "The It List", "Fashion Forward", "Bold & Beautiful", "The New Rules of Style", "Trend Alert", "Power Dressing"],
    referenceSublines: ["STYLE | The 50 pieces you need right now", "BEAUTY | Glow secrets from the pros", "FASHION | Street style stars to follow", "TRENDS | What's next in denim", "CULTURE | The women changing the game", "TRAVEL | Fashion capitals guide", "BEAUTY | 10 products under $30 that actually work", "STYLE | How to wear one dress 5 ways", "FASHION | Best of the runway decoded", "TRENDS | Color of the season revealed"]
  },
  {
    id: "harpers-bazaar",
    name: "Harper's Bazaar",
    uiFont: "'Libre Bodoni', serif",
    uiFontWeight: "700",
    gender: "female",
    category: "luxury",
    primaryColor: "#000000",
    accentColor: "#D4AF37",
    fontStyle: "Didot, serif",
    logoStyle: "Classic serif",
    logoColor: "Black/White",
    thumbnail: "/thumbnails/harpers-bazaar.jpg",
    editorialPersona: "You are the Art Director of Harper's Bazaar, the world's oldest fashion magazine (1867). You see fashion as ART. You are the heir to Alexey Brodovitch's legacy. Minimalism is your religion. White space is your weapon. You would rather have NO text than mediocre text. When you do write, it's one poetic phrase.",
    targetAudience: "Mature, affluent women 30-50, art collectors, gallery-goers, fashion-as-art appreciators",
    tone: "Artistic, museum-like, minimalist, intellectual, bold visually but restrained textually",
    focus: "Fashion as fine art, avant-garde photography, architectural fashion, museum-quality editorials",
    iconicElement: "Massive white space, artistic photography, classic 'Harper's BAZAAR' logo with distinctive apostrophe, almost no cover text",
    priceSegment: "luxury",
    coverLayoutDescription: "Sophisticated and spacious. Large amounts of white space. Logo is classic.",
    textDensity: "minimal",
    sublineCount: { min: 1, max: 2 },
    spatialGrid: "Maximalist space, minimalist content. Logo top-left or top-center. Subject artistically positioned — can be off-center, cropped unusually. Text: almost none. If present, bottom 10% only. 70%+ of cover surface is image or negative space.",
    materialFinish: "Premium matte paper, fine art print quality texture, deep rich blacks, subtle paper grain visible. Feels like a gallery print.",
    lightingDna: "Soft editorial lighting, 5400K, natural skin tones with artistic shadow play. Single large diffused light source creating dramatic but not harsh shadows. Chiaroscuro influence. Skin looks real, not polished.",
    typographyLayout: "Harper's: thin italic serif, 24-30pt. BAZAAR: bold serif, 40-48pt, ALL-CAPS. Body text (if any): thin serif, 7-8pt. Extreme minimalism.",
    logoPlacement: "'Harper's BAZAAR' — 'Harper's' in elegant thin italic serif, 'BAZAAR' in bold serif ALL-CAPS directly below. Positioned top-left or top-center. The logo has a distinctive apostrophe. Color: black or white.",
    headlineRules: "One poetic word or very short phrase. Maximum 3 words. Often just a concept or an emotion. No numbers. No questions. No exclamation marks. It should feel like the title of an art exhibition.",
    sublineCategories: ["FASHION", "ART", "DESIGN", "CULTURE"],
    coverTextStyle: "Almost no cover text. If present: 1-2 lines maximum, very thin serif, 7-8pt, positioned discretely at bottom-center or bottom-left. MASSIVE amounts of white/negative space.",
    colorInstructions: "Black and white dominant. Minimal color — when used, it's bold and singular (one accent color). High contrast. The text is always monochrome — black or white only. Never colorful text.",
    clothingGuide: "Avant-garde, architectural fashion. Sculptural silhouettes. Think Rei Kawakubo, Rick Owens, Azzedine Alaïa. Fashion that looks like wearable art or sculpture. Unconventional textures, dramatic shapes. Monochrome or single bold color.",
    poseGuide: "Artistic, often unconventional. The model may not face the camera. Angular poses, architectural body positions. Can be seated in an unusual way, draped over furniture, or in a dance-like position.",
    backgroundGuide: "Minimal and architectural. White studio, concrete wall, geometric shapes, or a single dramatic element. Massive negative space. Never busy.",
    referenceHeadlines: ["Sublime", "The New Light", "Infinite", "Form", "Silence", "The Art of Being", "Presence", "Awakening"],
    referenceSublines: ["FASHION | When fabric becomes sculpture", "ART | The eye of the new generation", "DESIGN | The architects of elegance", "CULTURE | A moment of pure beauty"]
  },
  {
    id: "cosmopolitan",
    name: "Cosmopolitan",
    uiFont: "'Dancing Script', cursive",
    uiFontWeight: "700",
    gender: "female",
    category: "lifestyle",
    primaryColor: "#FF007F",
    accentColor: "#FDE047",
    fontStyle: "Cursive/Italic serif",
    logoStyle: "Feminine script",
    logoColor: "Pink/Magenta",
    thumbnail: "/thumbnails/cosmopolitan.jpg",
    editorialPersona: "You are the Editor-in-Chief of Cosmopolitan. You are the ultimate 'Fun Fearless Female' — bold, direct, fun, a little provocative, and completely unapologetic. You LOVE numbers in headlines. You make big promises. You talk about sex, love, career, and confidence without taboo. You use exclamation marks. You use question marks. You are a best friend giving advice at a bar.",
    targetAudience: "Young women 18-34, confident, dating, career-building, socially active",
    tone: "Bold, playful, provocative, empowering, direct, fun, unapologetic",
    focus: "Relationships, sex, career empowerment, body confidence, dating, beauty",
    iconicElement: "Busy cover packed with headlines, pink/magenta branding, provocative sex-related headlines, numbers and promises",
    priceSegment: "budget",
    coverLayoutDescription: "Energetic and busy. Multiple headlines of varying sizes. Text in 'bursts'.",
    textDensity: "dense",
    sublineCount: { min: 6, max: 10 },
    spatialGrid: "BUSY grid filling all available space. Logo TOP 15%. Main headline LEFT at 40-60% height. Secondary headlines scattered in ALL margins — left, right, bottom. No area is 'clean' — every margin has text. Subject centered, with decolletage visible, face at ~35% from top.",
    materialFinish: "Standard high-gloss newsstand finish, high-saturation ink, bright whites, punchy contrast.",
    lightingDna: "Bright pop lighting, 6000K, energetic and fully saturated. Strong front fill-flash effect. Minimal shadows — the subject is evenly lit and glowing. Skin looks warm, healthy, and radiant. No dramatic shadows.",
    typographyLayout: "Cosmo logo: distinctive cursive/italic, 36-44pt. Main headline: bold sans-serif (Franklin Gothic style), 24-30pt. Numbers: 30-40pt bold. Secondary: 10-14pt mixed weights. Everything is bold, colorful, competing.",
    logoPlacement: "'Cosmopolitan' (or 'Cosmo' on some covers) in a distinctive cursive/italic serif font, large, spanning most of the width in the top 15%. Color: pink/magenta (#FF007F), white, or occasionally yellow. Always fully visible above model's head.",
    headlineRules: "ALWAYS uses numbers or strong action verbs. Provocative but empowering — never degrading. Frequently about sex/love/relationships. Uses '!', '?', and '...' freely. Big promises and reveals. Maximum 8 words.",
    sublineCategories: ["SEX & LOVE", "CAREER", "BEAUTY", "FASHION", "BODY", "CONFIDENCE", "DATING", "FUN"],
    coverTextStyle: "DENSE. 6-10 headlines filling every available space around the model. Main headline: bold sans-serif, 24-30pt, positioned LEFT of model at eye-level. Secondary headlines: various sizes (10-16pt), scattered in ALL quadrants — top-left, bottom-left, bottom-right. Colors: a MIX of hot pink, yellow (#FFD700), white, and occasionally orange.",
    colorInstructions: "VIBRANT. Pink/magenta dominant. Yellow for accent. White for readability. Occasional orange or red. Background should be bright and saturated. Never muted, never dark, never somber.",
    clothingGuide: "Sexy but not vulgar. Figure-hugging dresses, bold necklines, statement party wear. Can be a power suit with a flirty twist. Bright colors or classic black. Think 'going out' outfit — date night or girls' night.",
    poseGuide: "Confident and direct. Hands on hips, looking straight into camera with a knowing smile or flirty smirk. Shoulders back, body open and confident. Can be slightly leaning forward. Always facing camera directly.",
    backgroundGuide: "Bright, saturated solid color — hot pink, coral, bright blue, yellow. Or clean studio white. Never dark, never moody, never artsy.",
    referenceHeadlines: ["75 Sex Moves He'll Beg For", "Your Hottest Year Yet!", "Fun Fearless & Fabulous", "The Confidence Issue", "Get The Job & The Guy", "50 Things About Men", "His #1 Secret Fantasy", "Love Your Body Special"],
    referenceSublines: ["SEX & LOVE | 50 ways to drive him wild tonight", "CAREER | How to ask for the raise you deserve", "BEAUTY | The $10 product that changed everything", "FASHION | Date night looks that slay", "BODY | Feel amazing naked — starting now", "CONFIDENCE | Why being 'too much' is your superpower", "DATING | Red flags you're definitely ignoring", "FUN | 25 adventures for your bucket list"]
  },
  {
    id: "glamour",
    name: "Glamour",
    uiFont: "'Josefin Sans', sans-serif",
    uiFontWeight: "700",
    gender: "female",
    category: "lifestyle",
    primaryColor: "#000000",
    accentColor: "#F43F5E",
    fontStyle: "Rounded sans-serif",
    logoStyle: "Feminine sans-serif",
    logoColor: "Pink/White/Black",
    thumbnail: "/thumbnails/glamour.jpg",
    editorialPersona: "You are the Editor of Glamour. You are a warm, inclusive, empowering friend. You celebrate REAL women — all sizes, all backgrounds. Your 'Women of the Year' awards are prestigious. You balance beauty with substance. You're positive without being naive. Body positivity is core to your identity. You never shame, you always uplift.",
    targetAudience: "Women 18-40, inclusive mindset, beauty-lovers who also care about substance",
    tone: "Warm, friendly, inclusive, empowering, positive, approachable",
    focus: "Real beauty, self-improvement, empowerment, inclusivity, wellness, practical beauty tips",
    iconicElement: "'Women of the Year' awards, body positivity, inclusive casting, balance of beauty and substance",
    priceSegment: "budget",
    coverLayoutDescription: "Vibrant and empowering. Focus on beauty and real-life stories.",
    textDensity: "moderate",
    sublineCount: { min: 4, max: 7 },
    spatialGrid: "Balanced friendly layout. Logo TOP 12%. Headlines in neat columns LEFT and RIGHT. Good spacing between elements. Subject centered with warm, open body language.",
    materialFinish: "Smooth satin finish, natural skin texture preservation, balanced warm contrast.",
    lightingDna: "Warm beauty lighting, 4500K golden tone, soft and flattering. Large diffused light source creating a warm glow. Minimal shadows. Skin looks naturally luminous and healthy.",
    typographyLayout: "Glamour: rounded feminine sans-serif, 50-60pt. Headlines: rounded bold sans-serif, 16-20pt. Sublines: 9-11pt. Clean, organized hierarchy.",
    logoPlacement: "'Glamour' in a rounded, feminine sans-serif font, positioned top-center in the top 12%. Color: pink, white, or black. Warm and inviting, not sharp or aggressive.",
    headlineRules: "Empowering and positive. Uses 'You' and 'Your' to feel personal. Can include numbers for beauty lists. Never negative, never shaming. Feels like a supportive friend giving advice. Maximum 6 words.",
    sublineCategories: ["BEAUTY", "WELLNESS", "EMPOWERMENT", "STYLE", "SELF-CARE", "CONFIDENCE", "REAL TALK"],
    coverTextStyle: "Balanced — not as busy as Cosmo, not as minimal as Vogue. 4-7 headlines positioned LEFT and RIGHT of model in clean columns. Warm colors: pink, soft purple, white. Main headline: 16-20pt bold rounded sans-serif.",
    colorInstructions: "Warm and inviting. Pink (#F43F5E), soft lavender, warm coral, white. Never harsh. Never neon. The palette should feel like a warm hug — soft but vibrant.",
    clothingGuide: "Accessible elegance. Classic wrap dress, smart casual, knitwear, comfortable but stylish. Think 'best version of everyday' — not haute couture, not gym clothes. Colors: warm tones, pastels, or confident jewel tones.",
    poseGuide: "Natural, warm smile. Relaxed and approachable. Sitting comfortably or standing with a welcoming posture. Not stiff, not overly posed. Eye contact with camera but soft, not intense.",
    backgroundGuide: "Soft, warm tones — pale pink, lavender, soft peach, or clean white. Warm and inviting. Never harsh or clinical.",
    referenceHeadlines: ["Your Best Life Now", "Feel Good Guide", "You Are Enough", "Best of Beauty", "The Self-Care Issue", "Glow From Within", "Women of the Year", "Find Your Power"],
    referenceSublines: ["BEAUTY | 25 products our editors swear by", "WELLNESS | The morning routine that changed my life", "EMPOWERMENT | Why saying no is a superpower", "STYLE | 10 outfits that make you feel amazing", "SELF-CARE | A guide to actually relaxing", "CONFIDENCE | Real women share their glow-up stories", "REAL TALK | What nobody tells you about your 30s"]
  },
  {
    id: "vanity-fair",
    name: "Vanity Fair",
    uiFont: "'Playfair Display', serif",
    uiFontWeight: "400",
    gender: "female",
    category: "luxury",
    primaryColor: "#000000",
    accentColor: "#D4AF37",
    fontStyle: "Classic serif",
    logoStyle: "Iconic serif ALL-CAPS",
    logoColor: "White/Black",
    thumbnail: "/thumbnails/vanity-fair.jpg",
    editorialPersona: "You are the Editor of Vanity Fair. You cover Hollywood, politics, and scandal with intellectual wit. You're the publication that broke the Harvey Weinstein story. Your covers are cinematic — think Annie Leibovitz. You feature group portraits for the Hollywood Issue. Your headlines are few but powerful. You're prestigious, sharp, sometimes sarcastic.",
    targetAudience: "Educated adults 30-55, pop culture followers, film/TV industry, political junkies",
    tone: "Intellectual, sharp, witty, cinematic, prestigious, occasionally sarcastic",
    focus: "Hollywood, pop culture, political scandals, long-form investigative journalism, power and fame",
    iconicElement: "Hollywood Issue, Annie Leibovitz photography, cinematic group portraits, white/cream backgrounds",
    priceSegment: "premium",
    coverLayoutDescription: "Cinematic and prestigious. Often features group portraits or high-concept solo shots.",
    textDensity: "minimal",
    sublineCount: { min: 1, max: 3 },
    spatialGrid: "Cinematic wide-feel. Logo TOP 15% centered. Celebrity NAME large in bottom 30%. Headline minimal, bottom-weighted. Massive image dominance.",
    materialFinish: "Heavyweight archival quality paper, rich ink depth, subtle warm texture. Museum-quality print feel.",
    lightingDna: "Cinematic Rembrandt or split lighting, 5200K, dramatic and prestigious. Deep depth of field. Hard shadows for drama. Like an Annie Leibovitz portrait — every shadow tells a story.",
    typographyLayout: "VANITY FAIR: classic serif, 48-56pt, ALL-CAPS, wide tracking. Celebrity name: 20-24pt serif. Headlines: 12-14pt serif italic. Tight, authoritative.",
    logoPlacement: "'VANITY FAIR' in classic serif ALL-CAPS, wide tracking, positioned in the top 15%. Usually WHITE text over darker image, or BLACK text over light background. Prestigious and iconic.",
    headlineRules: "One powerful phrase that sounds like a movie title or a Pulitzer headline. Direct, impactful, sometimes with a hint of drama. Maximum 5 words.",
    sublineCategories: ["HOLLYWOOD", "POLITICS", "CULTURE", "POWER", "SCANDAL"],
    coverTextStyle: "Very minimal. The celebrity's NAME often appears large (18-24pt serif). One main headline below or beside the name (12-14pt). Maybe 1-2 discreet sublines. Total text area under 15%. Color: white or cream.",
    colorInstructions: "Creamy whites, deep blacks, champagne gold (#D4AF37) as rare accent. Background: often white/cream studio, or dramatic dark. Text: white or black only. Never colorful text.",
    clothingGuide: "Red carpet glamour or power dressing. Classic Hollywood: tuxedos, gowns, tailored suits. For men: impeccable suit or dramatic formal. For women: statement gown or sharp tailored look.",
    poseGuide: "Cinematic and dramatic. Like a still from an award-winning film. Dramatic lighting creating deep shadows. Can be seated in a grand chair, leaning against a doorframe, or in a powerful standing pose.",
    backgroundGuide: "Classic portrait studio: white/cream seamless, ornate room, or dramatic minimal set. Cinematic depth of field. Grand, prestigious.",
    referenceHeadlines: ["The Hollywood Issue", "The Power of Truth", "A Star is Reborn", "The Untold Story", "Behind the Curtain", "Legends Only", "The Reinvention", "Power & Glory"],
    referenceSublines: ["HOLLYWOOD | Inside the year's most anticipated film", "POLITICS | The scandal that shook Washington", "CULTURE | Why this moment matters", "POWER | The new guard of Hollywood"]
  },
  {
    id: "allure",
    name: "Allure",
    uiFont: "'Cormorant Garamond', serif",
    uiFontWeight: "300",
    gender: "female",
    category: "lifestyle",
    primaryColor: "#000000",
    accentColor: "#E11D48",
    fontStyle: "Clean modern sans-serif",
    logoStyle: "Modern sans-serif",
    logoColor: "Black/White",
    thumbnail: "/thumbnails/allure.jpg",
    editorialPersona: "You are the Beauty Director of Allure. You are 100% focused on beauty — skincare, makeup, hair. You are science-backed and product-driven. Your 'Best of Beauty' awards are the industry gold standard. You test everything. You give expert recommendations with warmth. You know the difference between retinol and retinal, and you can explain it simply.",
    targetAudience: "Beauty enthusiasts 18-40, skincare addicts, product reviewers, beauty professionals",
    tone: "Expert, warm, scientific but accessible, product-driven, authoritative on beauty",
    focus: "100% beauty — skincare science, makeup trends, hair, product reviews, ingredient deep-dives",
    iconicElement: "'Best of Beauty' awards (industry gold standard), extreme close-ups of faces, scientific beauty approach",
    priceSegment: "mid",
    coverLayoutDescription: "Beauty-focused. Often features extreme close-ups of faces.",
    textDensity: "moderate",
    sublineCount: { min: 4, max: 6 },
    spatialGrid: "Macro beauty focus. Logo TOP 10%. Headlines framing the face — LEFT and BOTTOM. The face takes up 70%+ of cover. Text positioned to complement, never obstruct.",
    materialFinish: "Glossy finish optimized for skin detail reproduction, high-detail ink, clean bright whites.",
    lightingDna: "Macro beauty ring-light setup, 5600K, ultra-sharp skin detail. Ring light reflections visible in eyes. Perfect even illumination showing every pore and texture. Skin looks real and detailed.",
    typographyLayout: "Allure: clean sans-serif, 44-52pt. Headlines: 16-20pt sans-serif. Sublines: 9-10pt. Clean, modern hierarchy.",
    logoPlacement: "'Allure' in clean modern sans-serif, positioned top-center in top 10%. Simple, elegant, not competing with the beauty visuals. Color: black or white.",
    headlineRules: "Product-focused and expert. Can use numbers for product lists. Scientific but warm. Always about beauty/skincare/hair. Maximum 5 words.",
    sublineCategories: ["SKINCARE", "MAKEUP", "HAIR", "NAILS", "WELLNESS", "BEST OF BEAUTY", "INGREDIENTS"],
    coverTextStyle: "Clean and organized. 4-6 headlines in neat arrangement. Main headline: 16-20pt clean sans-serif. Sublines: 9-10pt. Colors: mix of black, white, and one accent color (coral or magenta).",
    colorInstructions: "Clean and beauty-focused. Pastel pinks, corals, soft whites, with pops of bright magenta or coral (#E11D48). Background: often light/bright to showcase skin detail. Never dark or moody.",
    clothingGuide: "Minimal — the focus is on the FACE. If visible: simple elegant neckline, strapless, or bare shoulders. Nothing that competes with the beauty focus. Neutral colors.",
    poseGuide: "EXTREME CLOSE-UP of the face — beauty macro shot. Perfect skin detail visible. Head slightly tilted, soft expression, looking into camera. Think beauty campaign, not fashion editorial.",
    backgroundGuide: "Light, clean — white, soft pink, or bright solid color that doesn't compete with skin tones.",
    referenceHeadlines: ["Best of Beauty", "The Skincare Reset", "Glow Guide", "Science of Great Skin", "The Beauty Issue", "Clear Skin Secrets", "Hair Revolution", "New Beauty Rules"],
    referenceSublines: ["SKINCARE | The ingredient derms are obsessing over", "MAKEUP | 15 foundations tested on every skin tone", "HAIR | Color trends that actually last", "NAILS | The gel alternative that won't wreck your nails", "WELLNESS | How your gut affects your glow", "BEST OF BEAUTY | Our editors tested 500 products — here are the winners"]
  },
  {
    id: "marie-claire",
    name: "Marie Claire",
    uiFont: "'Cormorant Garamond', serif",
    uiFontWeight: "600",
    gender: "female",
    category: "lifestyle",
    primaryColor: "#000000",
    accentColor: "#BE123C",
    fontStyle: "Elegant serif",
    logoStyle: "LOWERCASE elegant serif",
    logoColor: "Black/White",
    thumbnail: "/thumbnails/marie-claire.jpg",
    editorialPersona: "You are the Editor of Marie Claire. You believe fashion and social justice are NOT mutually exclusive. You cover women's rights globally. Your reader is intelligent, socially conscious, and well-dressed. You mix accessible luxury with stories about women changing the world. You're inspiring without being preachy.",
    targetAudience: "Socially conscious women 25-45, globally aware, intelligent, fashion-meets-substance seekers",
    tone: "Inspiring, socially engaged, intelligent, elegant but grounded, globally conscious",
    focus: "Fashion + social justice, women's rights, global perspective, accessible luxury, career empowerment",
    iconicElement: "Lowercase 'marie claire' logo, global diversity in casting, fashion + social cause mix",
    priceSegment: "mid",
    coverLayoutDescription: "Empowering and balanced. Mix of fashion and serious journalism.",
    textDensity: "moderate",
    sublineCount: { min: 4, max: 6 },
    spatialGrid: "Balanced structured grid. Logo TOP 12% (lowercase). Headlines in organized columns LEFT and RIGHT. Subject centered. Text coverage ~20%.",
    materialFinish: "Standard quality magazine stock, balanced saturation, realistic and authentic feel.",
    lightingDna: "Natural daylight simulation, 5500K, honest and clean. Soft directional light creating gentle shadows. Skin looks real and diverse. Warm but not artificial.",
    typographyLayout: "marie claire: elegant serif, LOWERCASE, 36-44pt. Headlines: serif, 14-18pt. Sublines: 9-10pt. Balanced, readable.",
    logoPlacement: "'marie claire' in LOWERCASE elegant serif — this is distinctive and recognizable. Positioned top-center in top 12%. Color: black or white. The lowercase is part of the brand identity.",
    headlineRules: "Inspiring and substantive. About women making a difference, or fashion with purpose. Never frivolous. Can include numbers for style lists. Maximum 6 words.",
    sublineCategories: ["FASHION", "WOMEN", "CAREER", "GLOBAL", "BEAUTY", "SOCIAL CHANGE", "EMPOWERMENT"],
    coverTextStyle: "Balanced and structured. 4-6 headlines in clean columns, LEFT and RIGHT. Main headline: 14-18pt elegant serif. Sublines: 9-10pt. Colors: warm earth tones, deep red (#BE123C), black, white.",
    colorInstructions: "Warm earth tones, deep reds, black, white. Sophisticated but approachable. Never neon, never garish. The palette should feel intelligent and grounded.",
    clothingGuide: "Accessible luxury with intelligence. Tailored blazers, elegant but practical dresses, smart separates. Think 'powerful woman at a global summit'.",
    poseGuide: "Confident, intelligent, grounded. Standing tall or seated with purpose. The pose should communicate 'I am making a difference in the world.' Direct, honest gaze.",
    backgroundGuide: "Clean and versatile — studio or minimal location. Can incorporate global elements subtly. Warm and natural lighting feel.",
    referenceHeadlines: ["Women Who Inspire", "The Change Makers", "Fashion With Purpose", "Global Beauty", "Voices of Change", "The Empowerment Issue", "Career Special", "Strength & Style"],
    referenceSublines: ["FASHION | The designers championing sustainability", "WOMEN | 10 leaders reshaping the world", "CAREER | How to negotiate like a diplomat", "GLOBAL | Beauty traditions from 5 continents", "BEAUTY | Clean beauty that actually works", "SOCIAL CHANGE | The organizations making real impact"]
  },
  {
    id: "people",
    name: "People",
    uiFont: "'Oswald', sans-serif",
    uiFontWeight: "700",
    gender: "female",
    category: "lifestyle",
    primaryColor: "#000000",
    accentColor: "#DC2626",
    fontStyle: "Bold sans-serif",
    logoStyle: "Bold sans-serif ALL-CAPS",
    logoColor: "Red/White",
    thumbnail: "/thumbnails/people.jpg",
    editorialPersona: "You are the Editor of People magazine. You are America's #1 celebrity magazine. You're warm, friendly, and NEVER mean. You celebrate celebrity weddings, babies, and 'Sexiest Man Alive.' You love EXCLUSIVE stories. You use yellow badges and 'EXCLUSIVE' labels. You're like a friendly neighbor who has all the celebrity gossip but tells it with love.",
    targetAudience: "Mass audience 18-65, celebrity news lovers, human interest story fans, Middle America",
    tone: "Warm, friendly, accessible, celebratory, positive, gossipy but kind",
    focus: "Celebrity news, weddings, babies, exclusive interviews, human interest, feel-good stories",
    iconicElement: "'PEOPLE' in bold red, 'Sexiest Man Alive,' 'EXCLUSIVE' badges, multiple small photos, tabloid energy with heart",
    priceSegment: "budget",
    coverLayoutDescription: "Friendly and celebrity-focused. Often features multiple smaller photos.",
    textDensity: "dense",
    sublineCount: { min: 5, max: 8 },
    spatialGrid: "Tabloid collage. Logo TOP centered in RED. Main headline large LEFT or bottom. EXCLUSIVE badge top-left or top-right with yellow background. Secondary headlines and inset photos scattered.",
    materialFinish: "Standard newsstand gloss, high-contrast bright colors, warm skin tones, accessible feel.",
    lightingDna: "Warm candid flash, 5800K, direct and friendly. Minimal artistic shadows. Even lighting that makes everyone look approachable.",
    typographyLayout: "PEOPLE: bold sans-serif, 56-64pt, ALL-CAPS, RED. Headlines: bold sans-serif, 20-28pt. EXCLUSIVE badge: 12pt bold caps on yellow. Sublines: 10-14pt. Busy, warm.",
    logoPlacement: "'PEOPLE' in bold sans-serif ALL-CAPS, positioned top-center. Color: RED (#DC2626) or WHITE — always highly visible. Very recognizable.",
    headlineRules: "Celebrity-focused, exclusive, personal. Uses 'EXCLUSIVE', 'INSIDE', 'FIRST LOOK.' Direct quotes from celebrities are common. Warm and celebratory. Maximum 8 words.",
    sublineCategories: ["EXCLUSIVE", "CELEBRITY", "LOVE & MARRIAGE", "FAMILY", "HUMAN INTEREST", "ROYAL", "TRIBUTE"],
    coverTextStyle: "BUSY tabloid style. Multiple headlines and sub-headlines filling margins. Main headline: 20-28pt bold sans-serif. 'EXCLUSIVE' badge: yellow background, bold caps. Colors: red, yellow (#FFD700), white, blue (#0284C7).",
    colorInstructions: "Red, white, yellow, blue. Very American newsstand palette. Bold and accessible. Yellow used for badges and highlights. Red for logo and accents. White for readability.",
    clothingGuide: "Whatever the celebrity would actually wear — not styled for fashion. Red carpet looks, casual paparazzi style, family photos. Authentic, not editorial.",
    poseGuide: "Warm and approachable. Smiling, happy, looking at camera. Can be a couple or family shot. Studio portrait with warm lighting OR paparazzi-style candid.",
    backgroundGuide: "Clean studio (white/gray) for main portrait, or real-life location for candid shots. Warm and accessible.",
    referenceHeadlines: ["EXCLUSIVE: Inside Their Wedding!", "World's Most Beautiful", "My New Life", "The Love Story", "Baby Joy!", "How We Made It Work", "Sexiest Man Alive", "The Truth About Us"],
    referenceSublines: ["EXCLUSIVE | First photos of their newborn", "CELEBRITY | Inside their stunning new home", "LOVE & MARRIAGE | The proposal nobody saw coming", "FAMILY | How they're raising their kids differently", "HUMAN INTEREST | The teacher who saved 30 lives", "ROYAL | Palace secrets revealed"]
  },
  {
    id: "grazia",
    name: "Grazia",
    uiFont: "'Bebas Neue', sans-serif",
    uiFontWeight: "400",
    gender: "female",
    category: "street",
    primaryColor: "#000000",
    accentColor: "#000000",
    fontStyle: "Sharp modern sans-serif",
    logoStyle: "Modern sans-serif ALL-CAPS",
    logoColor: "Black/White",
    thumbnail: "/thumbnails/grazia.jpg",
    editorialPersona: "You are the Editor of Grazia, the Italian-born weekly fashion magazine. You cover THIS WEEK's trends — not next season. Street style is your religion. You make high fashion accessible with 'Get The Look' features. You're fast, current, and shopping-oriented. Your reader wants to know WHAT to buy and WHERE to buy it, NOW.",
    targetAudience: "Young, fashion-forward women 20-35, trend followers, street style lovers, fast-fashion shoppers",
    tone: "Fast, current, trendy, accessible, shopping-oriented, street-smart",
    focus: "Weekly trends, street style, celebrity fashion, shopping guides, 'Get The Look' features",
    iconicElement: "Weekly publication cycle (more current), street style focus, Italian fashion heritage, 'Get The Look' features",
    priceSegment: "mid",
    coverLayoutDescription: "Chic and fast-paced. Focus on weekly trends and celebrity style.",
    textDensity: "moderate",
    sublineCount: { min: 4, max: 6 },
    spatialGrid: "Sharp European grid. Logo TOP 10%. Headlines in clean columns. Subject in dynamic street-style pose. Feels like a fashion editor's screen — organized, fast.",
    materialFinish: "Weekly magazine glossy stock, crisp reproduction, trend-focused vibrancy.",
    lightingDna: "Natural daylight / street-style photography feel, 5400K, dynamic and crisp. Outdoor feel even in studio — bright, clear, no dramatic shadows.",
    typographyLayout: "GRAZIA: sharp angular sans-serif, 48-56pt, ALL-CAPS. Headlines: sans-serif, 14-18pt. Sublines: 9-11pt. European precision.",
    logoPlacement: "'GRAZIA' in sharp modern sans-serif ALL-CAPS, positioned top-center in top 10%. Angular, European feel. Color: black or white.",
    headlineRules: "Trend-focused and shopping-oriented. Uses 'THIS WEEK', 'NOW', 'GET THE LOOK.' Short and punchy, feels current. Maximum 5 words.",
    sublineCategories: ["TRENDS", "STYLE", "SHOPPING", "CELEBRITY STYLE", "STREET STYLE", "BEAUTY", "GET THE LOOK"],
    coverTextStyle: "Modern and snappy. 4-6 short headlines, LEFT and RIGHT margins. Main: 14-18pt sharp sans-serif. Secondary: 9-11pt. Colors: black, white, red for accents.",
    colorInstructions: "Black, white, red accents. Clean and European. Minimal color palette. Sharp contrast. Not rainbow — disciplined.",
    clothingGuide: "Street style meets accessible fashion. Current season trends visible. Think Zara, COS, & Other Stories mixed with one designer piece.",
    poseGuide: "Street style energy. Walking, in motion, or a dynamic standing pose. Like a paparazzi shot of a fashion editor leaving a show. Natural, unstaged, cool.",
    backgroundGuide: "Urban/street setting — city sidewalk feel, architectural elements, or clean studio simulating street style. European city energy.",
    referenceHeadlines: ["Trend Alert!", "Get The Look", "This Week's Must-Haves", "Style Steal", "Street Smart", "The Edit", "Copy Her Style", "Runway to Real Life"],
    referenceSublines: ["TRENDS | 5 pieces every fashion girl is buying this week", "STYLE | The coat that's selling out everywhere", "SHOPPING | Under $100 finds that look expensive", "CELEBRITY STYLE | How to dress like her for less", "STREET STYLE | Best looks from Milan this week", "BEAUTY | The viral product worth the hype"]
  },
  {
    id: "gq",
    name: "GQ",
    uiFont: "'Montserrat', sans-serif",
    uiFontWeight: "900",
    gender: "male",
    category: "luxury",
    primaryColor: "#000000",
    accentColor: "#FFFFFF",
    fontStyle: "Bold geometric sans-serif",
    logoStyle: "Geometric sans-serif ALL-CAPS",
    logoColor: "White/Black",
    thumbnail: "/thumbnails/gq.jpg",
    editorialPersona: "You are the Creative Director of GQ — Gentlemen's Quarterly. You are the authority on men's style, culture, and coolness. You're sophisticated yet ironic, intellectual yet accessible. You define what 'cool' means for modern men. Your 'Men of the Year' issue is legendary. You blend fashion with deep cultural commentary, long-form journalism, and sharp wit.",
    targetAudience: "Style-conscious men 25-45, culture lovers, professionals who care about both looking good and being informed",
    tone: "Sophisticated, ironic, intelligent, modern-masculine, cool, sharp",
    focus: "Men's style, culture, politics, music, long-form profiles, 'what it means to be a man today'",
    iconicElement: "Bold 'GQ' two-letter logo, 'Men of the Year,' sharp editorial portraits, coolness factor",
    priceSegment: "premium",
    coverLayoutDescription: "Sharp and masculine. Iconic bold logo. Minimalist text.",
    textDensity: "minimal",
    sublineCount: { min: 3, max: 5 },
    spatialGrid: "Central power composition. GQ logo TOP behind subject's head. Subject dominates frame. Headlines in LOWER quadrants. Minimal text coverage. Image is king.",
    materialFinish: "Satin-finish premium paper, subtle lithography texture, luxury print quality. Rich blacks.",
    lightingDna: "Low-key dramatic chiaroscuro, 4000K warm key, hard side-lighting creating deep masculine shadows. Sharp rim light for separation. Moody, cinematic, GQ-signature look.",
    typographyLayout: "GQ: bold geometric sans-serif, 80-96pt. Headlines: bold sans-serif, 16-22pt. Sublines: 9-11pt. Tight tracking, sharp.",
    logoPlacement: "'GQ' in massive bold geometric sans-serif, positioned top-center, partially behind subject's head. The two letters are so iconic that even partial visibility is recognizable. Color: white or black.",
    headlineRules: "Cool, sharp, culturally aware. Can be ironic. About style, culture, or the person on the cover. Maximum 5 words. Never uses numbers in a listicle way.",
    sublineCategories: ["STYLE", "CULTURE", "MUSIC", "FILM", "INTERVIEW", "FASHION", "WATCHES"],
    coverTextStyle: "Minimal and sharp. 3-5 headlines, positioned in LOWER quadrants (left or right). Main headline: 16-22pt bold sans-serif. Celebrity name large. Sublines: 9-11pt. Colors: primarily white, with occasional red or blue accent.",
    colorInstructions: "Black, white, with strategic accent colors. Can use deep blue, rich red, or gold for single accents. Never pastel, never pink.",
    clothingGuide: "Impeccably styled men's fashion. Tailored suit (not corporate — fashion-forward), designer knitwear, luxury casual. Think Tom Ford meets Virgil Abloh.",
    poseGuide: "Confident, cool, and slightly relaxed. Weight on one leg, hands in pockets or adjusting jacket. Direct gaze with a hint of attitude — not smiling broadly.",
    backgroundGuide: "Studio portrait — dark dramatic background, or clean minimal setting. Architectural elements (modern furniture, luxury interior) acceptable. Moody, sophisticated.",
    referenceHeadlines: ["The Style Issue", "Icon of the Year", "The New Cool", "Man of the Moment", "Best Dressed", "The Culture Issue", "Future Forward", "Style & Substance"],
    referenceSublines: ["STYLE | The suit rules have changed forever", "CULTURE | Why this actor is the voice of a generation", "MUSIC | The artist redefining sound", "INTERVIEW | An exclusive conversation", "FASHION | Fall's essential wardrobe", "WATCHES | The timepiece worth the investment"]
  },
  {
    id: "esquire",
    name: "Esquire",
    uiFont: "'Libre Baskerville', serif",
    uiFontWeight: "700",
    gender: "male",
    category: "luxury",
    primaryColor: "#000000",
    accentColor: "#B91C1C",
    fontStyle: "Classic serif",
    logoStyle: "Classic serif with stylized E",
    logoColor: "Black/White/Red",
    thumbnail: "/thumbnails/esquire.jpg",
    editorialPersona: "You are the Literary Editor of Esquire. Your magazine published Hemingway, Fitzgerald, Mailer, and Talese. You are the thinking man's magazine. Deep essays, not surface-level style tips. Your reader has a bookshelf full of classics and a well-made scotch. You cover politics, culture, literature, and yes — style, but always with substance. Your 'What I've Learned' column is legendary.",
    targetAudience: "Educated men 30-50, readers, literary minds, culture-and-politics lovers who also appreciate good style",
    tone: "Literary, intellectual, witty, classic masculine, deep, thoughtful",
    focus: "Long-form essays, literary journalism, politics, culture, style with substance, 'What I've Learned'",
    iconicElement: "Literary heritage, 'What I've Learned' column, stylized 'E' in logo, dramatic artistic portraits",
    priceSegment: "premium",
    coverLayoutDescription: "Intellectual and minimalist. High-quality photography takes center stage.",
    textDensity: "moderate",
    sublineCount: { min: 3, max: 5 },
    spatialGrid: "Minimalist literary grid. Logo TOP centered. Subject in dramatic portrait — artistic lighting. Headlines LEFT in elegant columns. Intellectual feel.",
    materialFinish: "Premium matte stock, rich warm texture, intellectual print feel. Visible paper grain.",
    lightingDna: "Classic portrait lighting, 4800K warm tone. Rembrandt lighting or loop lighting creating artistic character-defining shadows. Soft fall-off. Timeless portraiture.",
    typographyLayout: "Esquire: distinctive serif with stylized E, 44-52pt. Headlines: classic serif, 14-18pt. Sublines: 9-11pt serif. Refined, literary.",
    logoPlacement: "'Esquire' in a distinctive classic serif font with a stylized 'E'. Positioned top-center. Elegant and literary. Color: black, white, or red.",
    headlineRules: "Intellectual and thought-provoking. Often starts with 'The Meaning of...' or 'What I've Learned.' Feels like the title of an essay or book chapter. Maximum 6 words.",
    sublineCategories: ["LITERATURE", "POLITICS", "STYLE", "CULTURE", "INTERVIEW", "ESSAY", "FILM"],
    coverTextStyle: "More text than GQ but still refined. 3-5 headlines in elegant serif arrangement. Main headline: 14-18pt classic serif. Sublines: 9-11pt. Colors: primarily white or cream.",
    colorInstructions: "Dark, masculine, literary. Deep navy, burgundy (#B91C1C), black, white, cream. Rich and warm. Think mahogany study room.",
    clothingGuide: "Classic with character. Tweed blazer, Oxford shirt, quality knitwear. Or dramatic formal — tuxedo for an artistic shot. Earth tones, navy, burgundy, charcoal.",
    poseGuide: "Thoughtful, dramatic, intellectual. Hand on chin, looking into distance with a contemplative gaze. Or leaning forward with intensity. The portrait should feel like it captures a person's inner life.",
    backgroundGuide: "Dark, moody, dramatic. Studio with rich dark background, or atmospheric location (old library, study). Dramatic shadow play is essential.",
    referenceHeadlines: ["The Meaning of Style", "What I've Learned", "An American Story", "The Last Interview", "A Life Examined", "The Thinking Man", "Letters from the Edge", "The Art of Living"],
    referenceSublines: ["LITERATURE | The novel that defines our era", "POLITICS | Inside the campaign nobody talks about", "STYLE | Why the best suit is the one with a story", "CULTURE | The filmmaker reshaping cinema", "INTERVIEW | A rare conversation with a legend"]
  },
  {
    id: "mens-health",
    name: "Men's Health",
    uiFont: "'Oswald', sans-serif",
    uiFontWeight: "900",
    gender: "male",
    category: "fitness",
    primaryColor: "#B91C1C",
    accentColor: "#000000",
    fontStyle: "Impact sans-serif",
    logoStyle: "Heavy sans-serif ALL-CAPS",
    logoColor: "Red/Black",
    thumbnail: "/thumbnails/mens-health.jpg",
    editorialPersona: "You are the Fitness Editor of Men's Health. You are the world's #1 men's fitness publication. You MOTIVATE, not intimidate. Every headline is a promise of transformation — specific, numbered, time-bound. You use science and results. Your reader wants ABS, MUSCLE, and CONFIDENCE, and you deliver a PLAN. You are a personal trainer in print.",
    targetAudience: "Fitness-focused men 25-45, gym-goers, health-conscious, transformation seekers",
    tone: "Motivating, direct, energetic, science-backed, results-oriented, action-driven",
    focus: "Fitness transformation, workouts, nutrition, mental health, body optimization",
    iconicElement: "Muscular cover models (achievable physique, not bodybuilder), bold red/black typography, numbers and promises everywhere",
    priceSegment: "budget",
    coverLayoutDescription: "Powerful and energetic. Bold, high-impact typography.",
    textDensity: "dense",
    sublineCount: { min: 6, max: 10 },
    spatialGrid: "Action-packed grid. Logo TOP 15% in bold. Main headline LEFT 40-60% with large numbers. Secondary headlines filling ALL margins. Model centered, shirtless, powerful.",
    materialFinish: "Durable glossy finish, high-impact saturated colors, high-contrast ink.",
    lightingDna: "High-contrast gym lighting, 5600K, muscle-defining shadows and rim-light pop. Hard side-lighting to define every muscle group. Rim light for body separation from background.",
    typographyLayout: "MEN'S HEALTH: massive bold sans-serif, 60-72pt, ALL-CAPS. Headlines: Impact-style sans-serif, 24-32pt. Numbers: 36-48pt bold. Sublines: 10-12pt. Dense, powerful.",
    logoPlacement: "'MEN'S HEALTH' in massive bold sans-serif ALL-CAPS, positioned in top 15%. Color: RED (#B91C1C) or BLACK. Very bold, very visible — the logo itself is muscular.",
    headlineRules: "ALWAYS includes a number and a time frame. Specific promises. Action-oriented verbs. Maximum 6 words.",
    sublineCategories: ["FITNESS", "NUTRITION", "MUSCLE", "FAT LOSS", "MENTAL HEALTH", "GROOMING", "PERFORMANCE"],
    coverTextStyle: "PACKED with information. 6-10 headlines filling all margins. Main headline: 24-32pt bold impact sans-serif. Numbers in headlines: 36-48pt bold for emphasis. Colors: red, black, white, yellow.",
    colorInstructions: "Red (#B91C1C), black, white, yellow for highlights. High-contrast, high-energy. Never muted, never pastel. The palette should feel like adrenaline.",
    clothingGuide: "Shirtless or tight athletic wear showing physique. If wearing clothes: performance athletic wear (compression shirt, training shorts). The body IS the story.",
    poseGuide: "Powerful, athletic, showing physique. Hands on hips or arms slightly flexed. Standing tall and broad. Muscles visible but not in a bodybuilding flex. Looking directly at camera.",
    backgroundGuide: "Clean studio — often dark (black/charcoal) to make the body pop, or high-key white. Never distracting. The body is the background.",
    referenceHeadlines: ["Get Abs in 4 Weeks", "Burn Fat Build Muscle", "Your Best Body Ever", "30-Day Total Transform", "Lean Strong Unstoppable", "The Muscle Issue", "Shred for Summer", "Peak Performance Plan"],
    referenceSublines: ["FITNESS | The 20-minute workout that torches calories", "NUTRITION | What to eat before and after every workout", "MUSCLE | 3 moves that build arms fast", "FAT LOSS | The science of burning stubborn belly fat", "MENTAL HEALTH | Why lifting weights saves your mind", "GROOMING | Look as good as you feel"]
  },
  {
    id: "forbes",
    name: "Forbes",
    uiFont: "'UnifrakturMaguntia', cursive",
    uiFontWeight: "400",
    gender: "unisex",
    category: "business",
    primaryColor: "#000000",
    accentColor: "#D4AF37",
    fontStyle: "Gothic/Blackletter serif",
    logoStyle: "Historical Gothic serif",
    logoColor: "White/Gold/Black",
    thumbnail: "/thumbnails/forbes.jpg",
    thumbnailMale: "/thumbnails/forbes-male.jpg",
    thumbnailFemale: "/thumbnails/forbes-female.jpg",
    editorialPersona: "You are the Editor of Forbes, the capitalist bible. You measure success in dollars, innovation, and impact. Your lists (Billionaires, 30 Under 30, Fortune 500) define who matters in business. You speak with authority about wealth, entrepreneurship, and power. Your reader is either rich or planning to be.",
    targetAudience: "Business leaders 30-60, entrepreneurs, investors, C-suite executives, wealth seekers",
    tone: "Authoritative, informative, prestigious, wealth-oriented, concrete, factual",
    focus: "Business, wealth, entrepreneurship, billionaires, lists and rankings, investment, innovation",
    iconicElement: "Gothic/Blackletter 'Forbes' logo, billionaire lists, portrait of success/power, business authority",
    priceSegment: "premium",
    coverLayoutDescription: "Corporate and structured. Gothic logo. List-focused text.",
    textDensity: "moderate",
    sublineCount: { min: 3, max: 5 },
    spatialGrid: "Symmetrical power composition. Logo TOP centered. Subject in power-pose, centered. Headlines in structured columns RIGHT side, Y:50-85%. Professional, hierarchical.",
    materialFinish: "Matte with spot-UV on logo, visible paper grain, sharp precise ink. Premium business publication feel.",
    lightingDna: "Rembrandt lighting, warm 3200K key with sharp cool rim for professional separation. Dramatic but not theatrical. Like a C-suite portrait by a top photographer.",
    typographyLayout: "Forbes: Gothic/Blackletter, 52-60pt. Headlines: traditional serif, 18-24pt. Sublines: 10-12pt. Professional hierarchy.",
    logoPlacement: "'Forbes' in distinctive Gothic/Blackletter serif, positioned in top 15%. Traditional, prestigious. Color: usually in the dark Forbes brand styling, or white on dark.",
    headlineRules: "Business-focused, often list-related. Uses numbers for rankings. Concrete and factual — no fluff. Maximum 6 words.",
    sublineCategories: ["BUSINESS", "WEALTH", "ENTREPRENEURSHIP", "INVESTING", "INNOVATION", "30 UNDER 30", "LEADERSHIP"],
    coverTextStyle: "Structured and professional. 3-5 headlines in right-aligned columns. Main headline: 18-24pt serif, formal. List headlines use numbers prominently. Colors: black, gold (#D4AF37), white.",
    colorInstructions: "Black, gold (#D4AF37), deep blue (#1D4ED8), white. The palette of old money and authority. Gold for prestige. Blue for trust. Black for power.",
    clothingGuide: "Power business attire. Impeccable suit and tie, or tech-mogul smart casual. The clothing communicates 'I am successful.' Navy or charcoal suit, white shirt, power tie.",
    poseGuide: "Power portrait. Arms crossed or hands clasped on table. Seated in executive chair or standing in a position of authority. Direct, confident gaze.",
    backgroundGuide: "Professional studio portrait — dark or gradient background. Can include subtle office/boardroom elements. The focus is the person's face and power.",
    referenceHeadlines: ["The Billionaires Issue", "30 Under 30", "America's Most Innovative", "Self-Made Empire", "The Future of Money", "Power Players", "Richest in Tech", "The Next Billion"],
    referenceSublines: ["BUSINESS | How this CEO turned $100 into $1 billion", "WEALTH | The investment strategy top earners swear by", "ENTREPRENEURSHIP | Startups disrupting everything", "INVESTING | Where to put your money right now", "INNOVATION | The companies building tomorrow"]
  },
  {
    id: "rolling-stone",
    name: "Rolling Stone",
    uiFont: "'Arvo', serif",
    uiFontWeight: "700",
    gender: "unisex",
    category: "lifestyle",
    primaryColor: "#B91C1C",
    accentColor: "#000000",
    fontStyle: "Red serif/script",
    logoStyle: "Iconic red serif",
    logoColor: "Red",
    thumbnail: "/thumbnails/rolling-stone.jpg",
    thumbnailMale: "/thumbnails/rolling-stone-male.jpg",
    thumbnailFemale: "/thumbnails/rolling-stone-female.jpg",
    editorialPersona: "You are the Editor of Rolling Stone, the voice of rock and roll since 1967. Hunter S. Thompson wrote for you. You ARE counterculture. You cover music, politics, and cultural revolution with attitude and edge. Your reader doesn't follow trends — they start them. You're irreverent, passionate, and always politically engaged. Rock is dead? Not on your watch.",
    targetAudience: "Music lovers 18-45, counterculture enthusiasts, politically engaged, arts and culture followers",
    tone: "Rebellious, edgy, passionate, politically engaged, irreverent, cool, critical",
    focus: "Music, rock culture, political commentary, counterculture, artist profiles, social justice",
    iconicElement: "Red 'Rolling Stone' logo, iconic artist portraits, counterculture heritage, Hunter S. Thompson legacy",
    priceSegment: "mid",
    coverLayoutDescription: "Edgy and pop-culture focused. Iconic serif logo.",
    textDensity: "minimal",
    sublineCount: { min: 2, max: 4 },
    spatialGrid: "Image-dominant layout. Logo TOP in red. Artist name LARGE in bottom 20%. Headline minimal, bottom-left. 80%+ is image.",
    materialFinish: "Uncoated paper feel, high-ink absorption, artistic gritty texture. Like a fine art print, not a glossy magazine.",
    lightingDna: "Gritty artistic lighting, 5000K, high-contrast with deep shadows. Can be dramatic stage lighting, or intimate and raw. Not polished — real and honest.",
    typographyLayout: "Rolling Stone: distinctive red serif, 36-44pt. Artist name: 24-32pt bold. Headlines: serif, 18-24pt. Sublines: 10-12pt. Minimal.",
    logoPlacement: "'Rolling Stone' in distinctive red serif/script font, positioned in top 15%. Iconic and instantly recognizable. Color: RED (#B91C1C).",
    headlineRules: "About the artist/person on the cover — their story, their music, their rebellion. Raw and direct. Often includes 'The' + noun structure. Maximum 5 words.",
    sublineCategories: ["MUSIC", "POLITICS", "CULTURE", "INTERVIEW", "AMERICAN LIFE"],
    coverTextStyle: "Minimal but impactful. 2-4 headlines, mostly in lower portion. Main headline: 18-24pt bold serif. Celebrity name: very large. Colors: white, yellow.",
    colorInstructions: "Red (logo), white, black. Occasional yellow. Raw, not polished. The palette should feel like a rock poster — bold, simple, not corporate.",
    clothingGuide: "Rock and roll aesthetic. Leather jacket, band tee, denim, or dramatic artistic outfit. NOT corporate, NOT suits. Can be disheveled, unbuttoned, raw.",
    poseGuide: "Artistic and expressive — NOT a corporate headshot. Can be provocative, vulnerable, defiant, or intimate. Musicians in their element. Politicians caught in a moment of truth.",
    backgroundGuide: "Can be anything — but with ATTITUDE. Dark moody studio, gritty urban, or unexpectedly vulnerable setting. Never corporate, never clean-cut.",
    referenceHeadlines: ["The Last Rock Star", "American Rebel", "Voice of a Generation", "The Revolution", "Born to Run", "Raw & Unfiltered", "Iconic", "Truth to Power"],
    referenceSublines: ["MUSIC | The album that changed everything", "POLITICS | The fight for America's soul", "CULTURE | Why this artist matters now more than ever", "INTERVIEW | The most honest conversation we've ever had"]
  },
  {
    id: "wired",
    name: "Wired",
    uiFont: "'Black Han Sans', sans-serif",
    uiFontWeight: "400",
    gender: "unisex",
    category: "tech",
    primaryColor: "#000000",
    accentColor: "#00FF00",
    fontStyle: "Geometric futuristic sans-serif",
    logoStyle: "Futuristic sans ALL-CAPS",
    logoColor: "Black/White/Neon",
    thumbnail: "/thumbnails/wired.jpg",
    thumbnailMale: "/thumbnails/wired-male.jpg",
    thumbnailFemale: "/thumbnails/wired-female.jpg",
    editorialPersona: "You are the Editor of Wired, Silicon Valley's bible. You document the digital revolution — AI, crypto, space, biotech. Your design is as innovative as the tech you cover. You use bold visual concepts, futuristic color palettes, and sometimes replace photos with CGI or data visualizations. You're optimistic about technology's potential while being honest about its risks.",
    targetAudience: "Tech enthusiasts 25-45, developers, Silicon Valley insiders, futurists, startup founders",
    tone: "Futuristic, intelligent, optimistic, innovative, visually bold, analytical",
    focus: "Technology, AI, science, innovation, digital culture, the future",
    iconicElement: "Bold visual concepts (not always photos), neon/electric colors, futuristic design, 'THE FUTURE OF...' headline format",
    priceSegment: "mid",
    coverLayoutDescription: "Tech-forward and futuristic. Often uses vibrant colors.",
    textDensity: "moderate",
    sublineCount: { min: 3, max: 5 },
    spatialGrid: "Experimental futuristic grid. Logo integrated into design. Headlines can be unconventionally placed. Text and image blur together as a unified design. Tech-forward layout.",
    materialFinish: "High-tech synthetic feel, neon-saturated ink, futuristic texture simulation.",
    lightingDna: "Futuristic neon lighting, 6500K cool with colored gel accents (blue, green). Sharp digital feel. Ring lights, LED panels, or fully synthetic lighting for CGI covers.",
    typographyLayout: "WIRED: geometric futuristic sans-serif, 52-64pt, ALL-CAPS. Headlines: same family, 20-28pt. Can include tech symbols or data. Experimental.",
    logoPlacement: "'WIRED' in geometric futuristic sans-serif ALL-CAPS, positioned top-center or stylized into the design. Color: can vary wildly — black, white, neon green, electric blue.",
    headlineRules: "Future-focused and conceptual. Often uses 'THE FUTURE OF...' format. About technology, AI, science, or innovation. Analytical but exciting. Maximum 6 words.",
    sublineCategories: ["AI", "TECH", "SCIENCE", "INNOVATION", "STARTUPS", "DIGITAL CULTURE", "FUTURE"],
    coverTextStyle: "Bold and innovative. 3-5 headlines integrated into a futuristic design. Main headline: 20-28pt geometric sans-serif. Colors: neon green (#00FF00), electric blue, white, black.",
    colorInstructions: "Futuristic palette: neon green (#00FF00), electric blue (#0066FF), hot pink, white on black. Bold, digital, screen-inspired.",
    clothingGuide: "Tech-mogul aesthetic: clean minimalist black turtleneck, fitted tech-wear, or futuristic designer pieces. Silicon Valley smart casual — no ties, no suits.",
    poseGuide: "Can be a traditional portrait of a tech leader (direct, intelligent gaze) OR a conceptual visual (CGI, data visualization, abstract). Clean, direct, slightly futuristic styling.",
    backgroundGuide: "Futuristic: neon-lit, data-stream inspired, abstract geometric, or clean dark with digital elements. Can be fully CGI/conceptual. Never traditional studio.",
    referenceHeadlines: ["The Future of AI", "Code Is King", "The Next Internet", "How AI Changes Everything", "The Algorithm", "Digital Revolution", "Beyond Human", "The New Reality"],
    referenceSublines: ["AI | The model that thinks for itself", "TECH | Inside the device that replaces your phone", "SCIENCE | The breakthrough nobody expected", "INNOVATION | 10 startups that will define the decade"]
  },
  {
    id: "maxim",
    name: "Maxim",
    uiFont: "'Oswald', sans-serif",
    uiFontWeight: "700",
    gender: "male",
    coverStarGender: "female",
    category: "lifestyle",
    primaryColor: "#000000",
    accentColor: "#B91C1C",
    fontStyle: "Bold aggressive sans-serif",
    logoStyle: "Bold sans ALL-CAPS",
    logoColor: "Red/Black",
    thumbnail: "/thumbnails/maxim.jpg",
    editorialPersona: "You are the Editor of Maxim. You are the ultimate men's entertainment magazine — fun, sexy, irreverent. You celebrate beautiful women, parties, and the good life. You have the humor of a guy's night out. Your 'Hot 100' list is legendary. You don't take yourself too seriously, but your photography is actually really good.",
    targetAudience: "Young men 18-35, entertainment seekers, nightlife fans, pop culture consumers",
    tone: "Fun, irreverent, sexy, humorous, provocative, party-lifestyle",
    focus: "Entertainment, attractive women, parties, humor, lifestyle, the good life",
    iconicElement: "'Hot 100' list, sexy cover photos, party lifestyle, irreverent humor",
    priceSegment: "budget",
    coverLayoutDescription: "Edgy and lifestyle-focused. Focus on celebrities and luxury.",
    textDensity: "moderate",
    sublineCount: { min: 4, max: 6 },
    spatialGrid: "Glamour-focused grid. Logo TOP 12%. Model dominant. Headlines in lower margins. Name of cover star large.",
    materialFinish: "High-gloss premium stock, rich saturated colors, luxury lifestyle feel.",
    lightingDna: "Glamour lighting, warm 5200K, high-saturation, beauty-enhancing. Soft fill with warm rim light. Skin glows. Colors are rich.",
    typographyLayout: "MAXIM: bold aggressive sans-serif, 56-64pt, ALL-CAPS. Headlines: bold sans-serif, 20-26pt. Sublines: 10-12pt. Bold, direct.",
    logoPlacement: "'MAXIM' in bold aggressive sans-serif ALL-CAPS, positioned in top 12%. Strong, masculine, red or black. Color: RED (#B91C1C) or BLACK.",
    headlineRules: "Fun, provocative, entertainment-focused. About the cover star, parties, or lifestyle. Can be cheeky and humorous. Maximum 6 words.",
    sublineCategories: ["ENTERTAINMENT", "WOMEN", "LIFESTYLE", "HUMOR", "TRAVEL", "PARTY", "GADGETS"],
    coverTextStyle: "Bold and direct. 4-6 headlines around model. Main headline: 20-26pt bold sans-serif. Model name: large and prominent. Colors: red, white, black.",
    colorInstructions: "Red, black, white. High contrast, masculine. Occasional gold for luxury editions. Bold and simple — never soft or pastel.",
    clothingGuide: "For female cover stars: glamorous — cocktail dress, swimwear, or elegant evening wear. For male features: casual luxury, leather jacket, designer casual.",
    poseGuide: "Glamorous and sexy. Confident, alluring poses — but classy not explicit. Eye contact with camera, confident smile or sultry expression.",
    backgroundGuide: "Glamorous studio — often dark or rich colored to make the subject pop. Can be luxury setting (hotel, pool). Warm and inviting.",
    referenceHeadlines: ["The Hot 100", "Party of the Year", "The Maxim Experience", "Living the Dream", "Sizzle Issue", "Best Night Ever", "Ultimate Guide", "Summer's Hottest"],
    referenceSublines: ["ENTERTAINMENT | The movie everyone will be talking about", "LIFESTYLE | The ultimate bachelor pad guide", "TRAVEL | 10 party destinations you need to hit", "HUMOR | Things every man has done but won't admit"]
  },
  {
    id: "popular-mechanics",
    name: "Popular Mechanics",
    uiFont: "'Russo One', sans-serif",
    uiFontWeight: "400",
    gender: "unisex",
    category: "tech",
    primaryColor: "#000000",
    accentColor: "#B91C1C",
    fontStyle: "Industrial/retro sans-serif",
    logoStyle: "Industrial sans-serif",
    logoColor: "Red/Black",
    thumbnail: "/thumbnails/popular-mechanics.jpg",
    thumbnailMale: "/thumbnails/popular-mechanics-male.png",
    thumbnailFemale: "/thumbnails/popular-mechanics-female.jpg",
    editorialPersona: "You are the Editor of Popular Mechanics, America's DIY bible since 1902. You explain how things WORK. You are the bridge between complex engineering and the average curious person. Your reader has a garage full of tools and a mind full of questions. You love cars, space, tools, and building things. You make science hands-on and practical.",
    targetAudience: "DIY enthusiasts 35-60, engineers, makers, car lovers, tool collectors, curious minds",
    tone: "Practical, educational, hands-on, curious, American maker spirit",
    focus: "DIY projects, how things work, cars, tools, space, science for practical people",
    iconicElement: "Industrial/retro aesthetic, 'How It Works' features, technical cutaway illustrations, American maker heritage",
    priceSegment: "budget",
    coverLayoutDescription: "Informative and technical. Focus on DIY and science.",
    textDensity: "moderate",
    sublineCount: { min: 4, max: 6 },
    spatialGrid: "Informative structured grid. Logo TOP. Technical imagery dominant. Headlines in organized columns. Can include technical callouts and diagrams.",
    materialFinish: "Durable practical stock, clear crisp reproduction, utilitarian feel.",
    lightingDna: "Industrial workshop lighting, 5000K, clear and even. Technical photography — sharp detail, minimal artistic shadow. Like a product shoot for tools.",
    typographyLayout: "Popular Mechanics: industrial retro sans-serif, 36-44pt. Headlines: industrial sans, 18-24pt. Sublines: 10-12pt. Structured, clear.",
    logoPlacement: "'Popular Mechanics' in an industrial/retro sans-serif font, positioned top-center. Has a distinctly American mechanical feel. Color: RED or BLACK on light background.",
    headlineRules: "Practical and action-oriented. Uses 'HOW TO', 'BUILD', 'THE FUTURE OF'. About things, machines, and projects — not people. Maximum 6 words.",
    sublineCategories: ["DIY", "CARS", "SCIENCE", "TOOLS", "SPACE", "HOME", "TECHNOLOGY"],
    coverTextStyle: "Informative and organized. 4-6 headlines in structured columns. Main headline: 18-24pt industrial sans-serif. Colors: red, blue, black, white.",
    colorInstructions: "Industrial palette: red, dark blue (#1E3A5F), black, white, steel gray. Mechanical, American, hands-on. Like the inside of a workshop.",
    clothingGuide: "N/A — covers often feature machines, cars, or technical subjects. If a person appears: work clothes, flannel shirt, tool belt. Practical, not fashion.",
    poseGuide: "Often NOT a person on the cover — it's a machine, car, tool, or technical cutaway. If a person: hands-on, working on something, in a workshop or garage.",
    backgroundGuide: "Workshop, garage, technical setting, or outdoor construction site. Can be a cutaway illustration of a machine. Technical, informative visual.",
    referenceHeadlines: ["Build This Workshop", "How Things Really Work", "Future Cars Revealed", "Your Next Great Project", "The Science of Speed", "Ultimate Tool Guide", "Space: The Next Frontier", "Engineering Marvels"],
    referenceSublines: ["DIY | Weekend projects that transform your home", "CARS | Inside the most advanced engine ever built", "SCIENCE | The physics behind everyday things", "TOOLS | The 10 tools every workshop needs"]
  },
  {
    id: "sports-illustrated",
    name: "Sports Illustrated",
    uiFont: "'Teko', sans-serif",
    uiFontWeight: "700",
    gender: "unisex",
    category: "lifestyle",
    primaryColor: "#B91C1C",
    accentColor: "#000000",
    fontStyle: "Bold italic sans-serif",
    logoStyle: "Athletic sans-serif ALL-CAPS",
    logoColor: "Red/White",
    thumbnail: "/thumbnails/sports-illustrated.jpg",
    thumbnailMale: "/thumbnails/sports-illustrated-male.jpg",
    thumbnailFemale: "/thumbnails/sports-illustrated-female.jpg",
    editorialPersona: "You are the Editor of Sports Illustrated, America's sports bible. You capture the DRAMA of sports — the victories, the heartbreaks, the legends. Your Swimsuit Issue is a cultural phenomenon. Your 'Sportsperson of the Year' matters. You tell sports stories like epic novels. Every game is a battle, every athlete is a warrior.",
    targetAudience: "Sports fans 18-55, athletes, team followers, Americana lovers",
    tone: "Passionate, dramatic, epic, analytical, energetic, patriotic",
    focus: "Sports action, athlete profiles, championship analysis, swimsuit issue, sportsperson of the year",
    iconicElement: "Bold red 'SI' logo, Swimsuit Issue, action photography as art, 'Sportsperson of the Year'",
    priceSegment: "budget",
    coverLayoutDescription: "Action-focused. Features iconic sports photography.",
    textDensity: "moderate",
    sublineCount: { min: 3, max: 5 },
    spatialGrid: "Action-dynamic grid. Logo TOP centered. Athlete in ACTION dominating frame. Headline dramatic, bottom or side. Dynamic angles.",
    materialFinish: "Athletic iconic gloss, high-action color saturation, dramatic contrast.",
    lightingDna: "High-speed action lighting, 5600K, sharp and dramatic. Freeze-frame quality. Rim light for athletic body separation. Stadium-like lighting.",
    typographyLayout: "SPORTS ILLUSTRATED: bold italic sans-serif, 40-48pt. Headlines: bold italic, 22-30pt. Sublines: 10-12pt. Dynamic, energetic.",
    logoPlacement: "'SPORTS ILLUSTRATED' in bold italic sans-serif, positioned top-center. Dynamic, athletic energy. Color: RED (#B91C1C) or WHITE.",
    headlineRules: "Epic and dramatic. About victories, championships, and athletic greatness. Feels like the opening of a sports documentary. Maximum 6 words.",
    sublineCategories: ["FOOTBALL", "BASKETBALL", "CHAMPIONSHIP", "ATHLETE PROFILE", "PREVIEW", "EXCLUSIVE"],
    coverTextStyle: "Athletic and dramatic. 3-5 headlines. Main headline: 22-30pt bold italic sans-serif. Colors: red, white, blue (American palette). Athlete name very prominent.",
    colorInstructions: "Red, white, blue — American sports palette. High energy. Can include team colors of featured athlete. Never muted.",
    clothingGuide: "Athletic: team jersey, sports uniform, or athletic wear. For swimsuit issue: swimwear. The clothing is always performance/sport-related.",
    poseGuide: "ACTION. Mid-play, celebrating a victory, intense athletic moment. Dynamic, dramatic, frozen-in-time action. Energy and motion are essential.",
    backgroundGuide: "Stadium, field, court, or dramatic studio shot with athletic energy. Can include crowd blur. Motion and energy.",
    referenceHeadlines: ["Champion of Everything", "The Greatest Ever", "Born to Compete", "Game of the Century", "Dynasty", "Unstoppable Force", "The Chosen One", "Road to Glory"],
    referenceSublines: ["CHAMPIONSHIP | Inside the game that changed history", "ATHLETE | The training secret behind the comeback", "PREVIEW | Everything you need to know about this season", "EXCLUSIVE | The untold story of the trade"]
  },
  {
    id: "time",
    name: "Time",
    uiFont: "'Libre Baskerville', serif",
    uiFontWeight: "700",
    gender: "unisex",
    category: "lifestyle",
    primaryColor: "#B91C1C",
    accentColor: "#FFFFFF",
    fontStyle: "Classic serif",
    logoStyle: "White serif ALL-CAPS",
    logoColor: "White",
    thumbnail: "/thumbnails/time.jpg",
    thumbnailMale: "/thumbnails/time-male.jpg",
    thumbnailFemale: "/thumbnails/time-female.jpg",
    editorialPersona: "You are the Editor of Time, the world's most recognized newsmagazine since 1923. Your RED BORDER is the most iconic design element in magazine history. You name the 'Person of the Year.' You cover global events with objectivity and weight. Your covers make history — they ARE history. Every cover is a document of its era.",
    targetAudience: "Global audience 25-60, news followers, politically informed, globally conscious citizens",
    tone: "Objective, serious, authoritative, global, historically significant",
    focus: "Global news, Person of the Year, political coverage, world events, historical significance",
    iconicElement: "THE RED BORDER — the single most recognizable design element in magazine history. 'TIME' in white serif inside the red border. 'Person of the Year.'",
    priceSegment: "premium",
    coverLayoutDescription: "Iconic red border. One main headline. Pure photojournalism.",
    textDensity: "minimal",
    sublineCount: { min: 0, max: 2 },
    spatialGrid: "RED BORDER frames EVERYTHING. TIME logo top-center inside border. Subject CENTERED in the frame created by the border. Single headline (if any) at bottom-center.",
    materialFinish: "Standard newsprint quality with matte red border. Historical archive ink feel. Documentary quality.",
    lightingDna: "Hard reportage lighting — direct, honest, high micro-contrast. Like news photography. Realistic skin detail, no glamour. The lighting should feel documentary and truthful.",
    typographyLayout: "TIME: classic serif, 60-72pt, ALL-CAPS, WHITE inside red border. Headlines (if any): serif, 14-18pt, centered. Absolute minimum text.",
    logoPlacement: "'TIME' in white serif ALL-CAPS, positioned inside THE RED BORDER at the very top-center. The red border frames the ENTIRE cover like a window. This is NON-NEGOTIABLE.",
    headlineRules: "One impactful headline or NONE (just the visual). When present: about the person/event featured — global significance. Maximum 5 words.",
    sublineCategories: ["NEWS", "GLOBAL", "POLITICS", "PERSON OF THE YEAR", "HISTORY"],
    coverTextStyle: "EXTREMELY MINIMAL. Often just TIME + the image. If headline present: centered at bottom, 14-18pt serif, white or black. The visual IS the story.",
    colorInstructions: "RED BORDER (#B91C1C) framing entire cover. White 'TIME' text. Inside: can be any color depending on the subject. The red border is SACRED — it never changes.",
    clothingGuide: "Whatever is appropriate to the news story. Political: suits. Military: uniforms. Cultural: relevant clothing. This is photojournalism — clothing is documentary.",
    poseGuide: "Photojournalistic portrait. Direct gaze into camera, or caught in a significant moment. The portrait should feel like a historical document. No glamour, no fashion — just truth.",
    backgroundGuide: "Inside the red border — either a clean portrait background or an illustration/artistic interpretation of the news story. Historical weight.",
    referenceHeadlines: ["Person of the Year", "The Year Ahead", "Is This the End?", "The New America", "The Fight for Tomorrow", "Hope", "The 100 Most Influential", "Can This Be Fixed?"],
    referenceSublines: ["GLOBAL | The crisis reshaping world order", "POLITICS | Inside the most consequential election"]
  }
];

